version: '3.8'

services:
  web:
    build: ./app
    command: bash -c "gunicorn base.wsgi:application --bind 0.0.0.0:8000  --timeout 600"
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "Screener2"
      POSTGRES_USER: "fr3sto"
      POSTGRES_PASSWORD: "endorphin25"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  postgres_data:
