version: '3.8'

services:
  web:
    build: ./app
    command: bash -c "python manage.py collectstatic --noinput && gunicorn base.wsgi:application --bind 0.0.0.0:8000  --timeout 600"
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
